version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - app-data:/usr/src/app
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: "mongodb://mongodb:27017" # Replace with your actual database name

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  app-data:
  mongodb_data:
